language: java

notifications:
  email: true

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9

sudo: false # faster builds

before_install:
  - pip install --user codecov

after_success:
  - codecov
